############################################
## 	Makefile for accel sensors devices
## 	Author:LongJiang
## 	Date:2015-05-14
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_N2DM_ACCELER) += n2dm.o

