############################################
## 	Makefile for sensors params
## 	Author:LongJiang
## 	Date:2013-09-13
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_SENSORS_PARAMS) += sensparams.o
