#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_5446) += focaltech_ts.o

focaltech_ts-y += focaltech_core.o
focaltech_ts-y += focaltech_ex_fun.o
focaltech_ts-y += focaltech_gesture.o
focaltech_ts-y += focaltech_flash.o

focaltech_ts-y += test_lib.a
