############################################
## 	Makefile for sensors devices
## 	Author:LongJiang
## 	Date:2013-09-13
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_TMD277X_ALSPROX)	+= tmd277x.o
