############################################
## 	Makefile for sensors devices
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_PA12200001_ALSPROX)			+= pa12200001.o
obj-$(CONFIG_YL_PA12200001_ALSPROX_HQ) += pa12200001_hq.o
