obj-$(CONFIG_USB_TYPEC_FUSB302) += fusb302.o
obj-$(CONFIG_USB_TYPEC_PD_SUPPORT) += usbpd.o
obj-$(CONFIG_USB_TYPEC_PD_SUPPORT) += vdm_bitfield_translators.o
obj-$(CONFIG_USB_TYPEC_PD_SUPPORT) += vdm_manager.o
