ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_YL_PM8916_VBUS)		+= yl_pm8916_vbus.o
obj-$(CONFIG_YL_ADC_BATTERY)		+= yl_adc_battery.o
obj-$(CONFIG_YL_FAN5405_CHARGER)	+= yl_fan5405_charger.o
obj-$(CONFIG_YL_BQ24157_CHARGER)	+= yl_bq24157_charger.o
obj-$(CONFIG_YL_LC709203_FUELGAUGE)	+= yl_lc709203_fuelgauge.o
obj-$(CONFIG_YL_BQ25890_CHARGER)        += bq25890-parallel.o
