############################################
## 	Makefile for acc sensors devices
## 	Author:LongJiang
## 	Date:2013-09-13
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_BMA2X2_ACCELER)		+= bma2x2/
obj-$(CONFIG_YL_LIS3DH_ACCELER)		+= lis3dh/
obj-$(CONFIG_YL_KIONIX_ACCELER)		+= kionix/
obj-$(CONFIG_YL_N2DM_ACCELER)           += n2dm/
