
# LED Platform Drivers
obj-$(CONFIG_LEDS_SGM3780_FLASH)	+= leds_sgm3780_flash.o
obj-$(CONFIG_LEDS_TORCH_ONLY_FLASH)	+= leds_torch_only_flash.o
# AW2013 LED
obj-$(CONFIG_YL_LEDS_AW2013)		+= aw-leds.o
obj-$(CONFIG_YL_LEDS_AW2013_HQ)		+= aw-leds-headquarter.o
# KTD2026 LED
obj-$(CONFIG_LEDS_KTD)			+=leds-ktd.o
