############################################
## 	Makefile for sensors devices
## 	Author:LongJiang
## 	Date:2013-09-13
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_SENSORS_PARAMS)		+= sensparams/
obj-$(CONFIG_YL_SENSORS_ALSPROX)	+= alsprox/
obj-$(CONFIG_YL_SENSORS_GSENSOR)	+= accel/
obj-$(CONFIG_YL_SENSORS_HALL)		+= hall/
obj-$(CONFIG_RAON_REMOTE_CTRL_SOC)	+= remote/
obj-$(CONFIG_IIO)	+= invensense/
