#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_BOOTREASON)	+= bootreason.o

#added by zhuhui 2014.2.28
obj-$(CONFIG_CREATE_NODE)	+= createnode.o

obj-y += yl_lcd.o

obj-$(CONFIG_INFRARED_UEI1700)	+= uei1700.o
