############################################
## 	Makefile for alsprox sensors devices
## 	Author:LongJiang
## 	Date:2013-09-13
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_LTR559_ALSPROX)         += ltr559/
obj-$(CONFIG_YL_LTR559_2INPUT_ALSPROX)         += ltr559_2input/
obj-$(CONFIG_YL_LTR558_ALSPROX)		+= ltr558/
obj-$(CONFIG_YL_TMD277X_ALSPROX)	+= tmd277x/
obj-$(CONFIG_YL_PA12200001_ALSPROX)        += pa12200001/
obj-$(CONFIG_YL_PA12200001_ALSPROX_HQ)        += pa12200001/
