obj-y += ft5x06_ts.o
#obj-y += ft5336_download_lib.o
#extlibs :=$(PWD)/drivers/input/touchscreen/focaltech/focal_test_lib.a
#ldflags-y += --whole-archive $(extlibs) --no-whole-archive
obj-y += lib/
