#
# Makefile for industrial I/O Magnetometer sensors
#

obj-$(CONFIG_YL_SENSORS_YAS533)	+= yas_mag_drv-yas532.o yas_mag_kernel.o
obj-$(CONFIG_YL_SENSORS_YAS537) += yas_mag_drv-yas537.o  yas_mag_kernel.o

obj-$(CONFIG_YL_SENSORS_AKM09911) += akm09911.o

