#
# Makefile for synaptics S2202/S3202
#
obj-y += synaptics_dsx_rmi_reflash.o
obj-y += synaptics_dsx_i2c.o
obj-y += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TS_TEST_REPORTING) += synaptics_dsx_test_reporting.o

